apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: BUILDAH_IMAGE
      description: Reference the image version of buildah.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the Dockerfile to build.
      default: .
  workspaces:
    - name: source
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /root/.docker/
  steps:
    - name: build
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) --isolation chroot $(params.CONTEXT) 
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
    - name: push
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        buildah --storage-driver=$(params.STORAGE_DRIVER) push \
          --authfile /root/.docker/.dockerconfigjson $(params.IMAGE) --isolation chroot
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}