apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: IMAGE_TAG
      description: Reference of the target image tag.
      default: latest
    - name: BUILDAH_IMAGE
      description: Reference the image version of buildah.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the Dockerfile to build.
      default: .
    - name: IMAGE_REGISTRY
      description: The Root url of the image registry.
      default: docker.io
    - name: IMAGE_REGISTRY_USER
      description: The secret name of the secret holding the username.
      default: image-registry-username
    - name: IMAGE_REGISTRY_PASS
      description: The secret name of the secret holding the password.
      default: image-registry-password
  workspaces:
    - name: source
  steps:
    - name: build
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        set +x
        buildah login \
          -u $IMAGE_REGISTRY_USER \
          -p $IMAGE_REGISTRY_PASS $(params.IMAGE_REGISTRY) > /dev/null
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE):$(params.IMAGE_TAG) --isolation chroot $(params.CONTEXT)
        buildah --storage-driver=$(params.STORAGE_DRIVER) push $(params.IMAGE):$(params.IMAGE_TAG)
        set -x
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: IMAGE_REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_USER)
              key: $(params.IMAGE_REGISTRY_USER)
        - name: IMAGE_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_PASS)
              key: $(params.IMAGE_REGISTRY_PASS)
    - name: trivy-scan
      image: docker.io/aquasec/trivy
      workingDir: $(workspaces.source.path)
      script: |
        trivy image $(params.IMAGE):$(params.IMAGE_TAG)
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: TRIVY_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_USER)
              key: $(params.IMAGE_REGISTRY_USER)
        - name: TRIVY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_PASS)
              key: $(params.IMAGE_REGISTRY_PASS)
    - name: push
      image: $(params.BUILDAH_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        set +x
        buildah login \
          -u $IMAGE_REGISTRY_USER \
          -p $IMAGE_REGISTRY_PASS $(params.IMAGE_REGISTRY) > /dev/null
        buildah --storage-driver=$(params.STORAGE_DRIVER) tag $(params.IMAGE):$(params.IMAGE_TAG) $(params.IMAGE):latest
        buildah --storage-driver=$(params.STORAGE_DRIVER) push $(params.IMAGE):latest
        set -x
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      env:
        - name: IMAGE_REGISTRY_USER
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_USER)
              key: $(params.IMAGE_REGISTRY_USER)
        - name: IMAGE_REGISTRY_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.IMAGE_REGISTRY_PASS)
              key: $(params.IMAGE_REGISTRY_PASS)
  volumes:
    - name: varlibcontainers
      emptyDir: {}
